version: '3.1'
services:
  portainer:
    # 该镜像地址应该改为自己的阿里云镜像仓库地址，暂时先使用这个
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/portainer
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/portainer_data/data:/data
      - ../data/portainer_data/public:/public
